"""Generates boilerplate integration code for selected models."""

def generate_transformers_snippet(
    model_id: str,
    pipeline_tag: str,
    target_device: str = "cpu",
    precision: str = "fp16"
) -> str:
    """Generates ready-to-run Python inference code."""
    device_arg = 'device="cuda"' if target_device == "gpu" else ('device="mps"' if target_device == "mps" else 'device="cpu"')
    torch_dtype = "torch.float16" if precision in ["fp16", "bf16"] and target_device != "cpu" else "torch.float32"

    return f'''# Auto-generated by ModelFit-MCP
import torch
from transformers import pipeline

print("Loading {model_id} on {target_device.upper()}...")

# Load pipeline with hardware-optimized device mapping
classifier = pipeline(
    task="{pipeline_tag}",
    model="{model_id}",
    {device_arg},
    torch_dtype={torch_dtype}
)

def run_inference(input_data):
    """
    Run inference on input (e.g. image path or URL for vision tasks).
    """
    results = classifier(input_data)
    return results

if __name__ == "__main__":
    print("Model {model_id} loaded successfully!")
'''


def generate_client_snippet(host: str = "127.0.0.1", port: int = 7860) -> str:
    """Generates Python client code consuming the local ModelFit micro-API."""
    return f'''# Connects to ModelFit Local Gateway
import requests

GATEWAY_URL = "http://{host}:{port}"

def predict(input_data):
    response = requests.post(f"{{GATEWAY_URL}}/predict", json={{"input": input_data}})
    response.raise_for_status()
    return response.json()["predictions"]

def swap_model(model_id, task="image-classification"):
    response = requests.post(f"{{GATEWAY_URL}}/swap", json={{"model_id": model_id, "task": task}})
    response.raise_for_status()
    return response.json()
'''
