"""Generates boilerplate integration code across multiple languages."""

from typing import List


def generate_transformers_snippet(
    model_id: str,
    pipeline_tag: str,
    target_device: str = "cpu",
    precision: str = "fp16"
) -> str:
    """Generates ready-to-run Python inference code."""
    device_arg = 'device="cuda"' if target_device == "gpu" else ('device="mps"' if target_device == "mps" else 'device="cpu"')
    torch_dtype = "torch.float16" if precision in ["fp16", "bf16"] and target_device != "cpu" else "torch.float32"

    return f'''# Auto-generated by ModelFit-MCP
import torch
from transformers import pipeline

print("Loading {model_id} on {target_device.upper()}...")

classifier = pipeline(
    task="{pipeline_tag}",
    model="{model_id}",
    {device_arg},
    torch_dtype={torch_dtype}
)

def run_inference(input_data):
    return classifier(input_data)

if __name__ == "__main__":
    print("Model {model_id} ready!")
'''


def generate_ensemble_snippet(
    model_ids: List[str],
    pipeline_tag: str = "image-classification",
    strategy: str = "weighted_average"
) -> str:
    """Generates Python code running an ensemble of lightweight models."""
    models_repr = repr(model_ids)
    return f'''# Auto-generated by ModelFit-MCP Ensemble Gateway
from modelfit.ensemble import EnsembleGateway

gateway = EnsembleGateway()
models = {models_repr}

def predict(input_data):
    return gateway.predict_ensemble(
        input_data=input_data,
        model_ids=models,
        pipeline_tag="{pipeline_tag}",
        strategy="{strategy}"
    )

if __name__ == "__main__":
    preds = predict("sample_input.jpg")
    for p in preds:
        print(f"{{p.label}}: {{p.score}} (votes: {{p.votes}})")
'''


def generate_client_snippet(host: str = "127.0.0.1", port: int = 7860) -> str:
    """Generates Python client code consuming the local ModelFit micro-API."""
    return f'''# ModelFit Local Python Client
import requests

GATEWAY_URL = "http://{host}:{port}"

def predict(input_data):
    resp = requests.post(f"{{GATEWAY_URL}}/predict", json={{"input": input_data}})
    resp.raise_for_status()
    return resp.json()["predictions"]

def swap_model(model_id, task="image-classification"):
    resp = requests.post(f"{{GATEWAY_URL}}/swap", json={{"model_id": model_id, "task": task}})
    resp.raise_for_status()
    return resp.json()
'''


def generate_flutter_snippet(host: str = "127.0.0.1", port: int = 7860) -> str:
    """Generates Dart / Flutter client code to consume ModelFit Local Gateway."""
    return f'''// ModelFit Flutter/Dart Client
import 'dart:convert';
import 'package:http/http.dart' as http;

class ModelFitClient {{
  final String gatewayUrl;

  ModelFitClient({{this.gatewayUrl = 'http://{host}:{port}'}});

  Future<List<Map<String, dynamic>>> predict(String inputData) async {{
    final response = await http.post(
      Uri.parse('$gatewayUrl/predict'),
      headers: {{'Content-Type': 'application/json'}},
      body: jsonEncode({{'input': inputData}}),
    );

    if (response.statusCode == 200) {{
      final data = jsonDecode(response.body);
      return List<Map<String, dynamic>>.from(data['predictions']);
    }} else {{
      throw Exception('Failed to predict: ${{response.body}}');
    }}
  }}

  Future<void> swapModel(String modelId, {{String task = 'image-classification'}}) async {{
    final response = await http.post(
      Uri.parse('$gatewayUrl/swap'),
      headers: {{'Content-Type': 'application/json'}},
      body: jsonEncode({{'model_id': modelId, 'task': task}}),
    );

    if (response.statusCode != 200) {{
      throw Exception('Failed to swap model: ${{response.body}}');
    }}
  }}
}}
'''


def generate_node_snippet(host: str = "127.0.0.1", port: int = 7860) -> str:
    """Generates Node.js / JavaScript client code."""
    return f'''// ModelFit Node.js / TypeScript Client
const GATEWAY_URL = 'http://{host}:{port}';

async function predict(inputData) {{
  const res = await fetch(`${{GATEWAY_URL}}/predict`, {{
    method: 'POST',
    headers: {{ 'Content-Type': 'application/json' }},
    body: JSON.stringify({{ input: inputData }})
  }});
  const data = await res.json();
  return data.predictions;
}}

async function swapModel(modelId, task = 'image-classification') {{
  const res = await fetch(`${{GATEWAY_URL}}/swap`, {{
    method: 'POST',
    headers: {{ 'Content-Type': 'application/json' }},
    body: JSON.stringify({{ model_id: modelId, task }})
  }});
  return await res.json();
}}
'''
